<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class CashWithdrawal extends Model
{
    use HasFactory;

    protected $fillable = [
        'cash_settlement_id','shift_id','expense_id','employee_id','amount','currency',
        'withdrawal_date','withdrawn_by_name','handed_by_name','notes',
        'withdrawal_type','exchange_to_currency','exchange_to_amount','funding_source','payment_account_id',
    ];

    protected $casts = [
        'amount'             => 'decimal:2',
        'exchange_to_amount' => 'decimal:2',
        'withdrawal_date'    => 'datetime',
    ];

    public function cashSettlement() { return $this->belongsTo(CashSettlement::class); }
    public function shift()          { return $this->belongsTo(Shift::class); }
    public function expense()        { return $this->belongsTo(\App\Models\Expense::class); }
    public function employee()       { return $this->belongsTo(\App\Models\Employee::class); }

    public function isAutoGenerated(): bool
    {
        return $this->expense_id !== null;
    }

    public function getTypeLabelAttribute(): string
    {
        return $this->withdrawal_type === 'currency_exchange' ? 'صرف عملة' : 'مصروف';
    }

    public function isExchange(): bool
    {
        return $this->withdrawal_type === 'currency_exchange';
    }

    public function getFundingSourceLabelAttribute(): string
    {
        return $this->funding_source === 'general_safe' ? 'الصندوق العام' : 'الوردية';
    }

    /** الوعاء المالي الذي خرج منه المبلغ (درج، خزنة، أو حساب بنكي). */
    public function paymentAccount()
    {
        return $this->belongsTo(PaymentAccount::class);
    }

    /**
     * السحبيات التي خرجت من نقدية الموظف فعلاً — دون ما مُوِّل من الصندوق العام.
     *
     * مصدرٌ واحد لهذا الفرق: ما خرج من الخزنة يُسجَّل ويُعرض في كشف الموظف
     * ليعرف أنه صرفه، لكنه لا يدخل حساب ما عليه — المال لم يمرّ بيده.
     */
    public function scopeFromShiftDrawer(\Illuminate\Database\Eloquent\Builder $query): \Illuminate\Database\Eloquent\Builder
    {
        return $query->where(function ($q) {
            $q->where('funding_source', '!=', 'general_safe')
              ->orWhereNull('funding_source');
        });
    }
}
